import { Profile, Product, Accessory } from './types';

export const ACCESSORIES: Accessory[] = [
    { id: 'vent_none', name: 'Bez wentylacji', category: 'Ventilation', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/ventilation/none.png' },
    { id: 'vent_standard', name: 'Nawiewnik Standard', category: 'Ventilation', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/ventilation/vent_standard.png' },
    { id: 'vent_hygro', name: 'Nawiewnik Higrosterowalny', category: 'Ventilation', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/ventilation/vent_hygro.png' },
    { id: 'vent_press', name: 'Nawiewnik Ciśnieniowy', category: 'Ventilation', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/ventilation/vent_press.png' },
    
    { id: 'handle_white', name: 'Klamka Biała (Standard)', category: 'Handles', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/handtag/handle_white.png' },
    { id: 'handle_silver', name: 'Klamka Srebrna', category: 'Handles', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/handtag/handle_silver.png' },
    { id: 'handle_gold', name: 'Klamka Złota', category: 'Handles', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/handtag/handle_gold.png' },
    { id: 'handle_black', name: 'Klamka Czarna', category: 'Handles', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/handtag/handle_black.png' },
    { id: 'handle_titan', name: 'Klamka Tytan', category: 'Handles', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/handtag/handle_titan.png' },
    { id: 'handle_brown', name: 'Klamka Brązowa', category: 'Handles', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/handtag/handle_brown.png' },
    
    { id: 'color_white', name: 'Biały (Standard)', category: 'Colors', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/farg/color_white.png' },
    { id: 'color_anthracite', name: 'Antracyt', category: 'Colors', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/farg/color_anthracite.png' },
    { id: 'color_oak', name: 'Złoty Dąb', category: 'Colors', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/farg/color_oak.png' },
    { id: 'color_walnut', name: 'Orzech', category: 'Colors', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/farg/color_walnut.png' },
    { id: 'color_winchester', name: 'Winchester', category: 'Colors', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/farg/color_winchester.png' },
    { id: 'color_grey', name: 'Szary', category: 'Colors', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/farg/color_grey.png' },
    
    { id: 'glass_2', name: '2-Szybowy', category: 'Glass', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/glass/glass_2.png' },
    { id: 'glass_3', name: '3-Szybowy', category: 'Glass', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/glass/glass_3.png' },
    { id: 'glass_4', name: '4-Szybowy (Premium)', category: 'Glass', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/glass/glass_4.png' },
    { id: 'glass_tempered', name: 'Hartowana', category: 'Glass', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/glass/glass_tempered.png' },
    { id: 'glass_security', name: 'Antywłamaniowa', category: 'Glass', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/glass/glass_security.png' },
    { id: 'glass_frosted', name: 'Mleczna', category: 'Glass', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/glass/glass_frosted.png' },
    { id: 'glass_acoustic', name: 'Dźwiękochłonna', category: 'Glass', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/glass/glass_acoustic.png' },
    { id: 'glass_solar', name: 'Przeciwsłoneczna', category: 'Glass', imageSrc: 'https://cdn.jsdelivr.net/gh/Macmus40/f-nster-konfigurator-mini/public/images/glass/glass_solar.png' },
];

// UWAGA: Wszystkie obrazy produktów można teraz wrzucać do folderu /public/images/
// z podziałem na podkatalogi: /fönster, /dörr, /terrassystem
// i odwoływać się do nich poprzez ścieżkę: '/images/[KATEGORIA]/nazwa_pliku.jpg'
// Przykład: imageSrc: '/images/fönster/okno-1.png'

export const PROFILES: Profile[] = [
    { 
        name: 'Iglo5', 
        type: 'PVC', 
        specs: { Uw: '0.89', dB: '32-44', chambers: '5', depth: '70mm' }, 
        imageSrc: 'https://www.fonsterfaktor.se/lib/uid2kb/IGLO5-m6tka1j4.png',
        description: 'Detta 5-kammarsystem kännetecknas av väldigt goda värmeisoleringsparametrar. En snövit profil i A-klass, tillverkad av enbart primärmaterial, vilket garanterar högsta kvalitet. Lämpar sig för både varmt och kallt klimat.'
    },
    { 
        name: 'Iglo5 Classic', 
        type: 'PVC', 
        specs: { Uw: '0.89', dB: '32-44', chambers: '5', depth: '70mm' }, 
        imageSrc: 'https://www.fonsterfaktor.se/lib/uid2kb/IGLO5clasicc-m6tka35j.png',
        description: 'Samma höga kvalitet som Iglo 5 men med en klassisk, rak profil. 5-kammarsystem med utmärkta isoleringsegenskaper och hållbarhet.'
    },
    { 
        name: 'Iglo Energy', 
        type: 'PVC', 
        specs: { Uw: '0.60', dB: '35-46', chambers: '7', depth: '82mm' }, 
        imageSrc: 'https://www.fonsterfaktor.se/lib/uid2kb/IGLO-Energy-m6tk9xpm.png',
        description: 'Innovativt 7-kammarsystem med central tätning av skummat EPDM. Världens första system med denna lösning, vilket garanterar de bästa parametrarna avseende energieffektivitet.'
    },
    { 
        name: 'Iglo Light', 
        type: 'PVC', 
        specs: { Uw: '0.80', dB: '34-45', chambers: '5', depth: '70mm' }, 
        imageSrc: 'https://www.fonsterfaktor.se/lib/uid2kb/IGLO-Light-m6tk9yz0.png',
        description: 'Smala profiler för maximalt ljusinsläpp. 5-kammarsystem med stilren design och smäckra ramar som ger upp till 10% mer ljus än standardfönster.'
    },
    { 
        name: 'Iglo Premier', 
        type: 'PVC', 
        specs: { Uw: '0.79', dB: '34-44', chambers: '7', depth: '82mm' }, 
        imageSrc: 'https://www.fonsterfaktor.se/lib/uid2kb/IGLO-Priner-m6tka08l.png',
        description: 'Ett modernt 5-kammarsystem som kombinerar estetik med funktionalitet. Ger god isolering och stabilitet för krävande miljöer.'
    },
    { 
        name: 'Softline', 
        type: 'TRÄ', 
        specs: { Uw: '0.80-1.2', dB: '32-42', chambers: 'Wood', depth: '68-88mm' }, 
        imageSrc: 'https://www.fonsterfaktor.se/lib/uid2kb/softline-m6tka5ul.png',
        description: 'Träfönster i furu eller meranti med klassisk elegans. Rundade profiler och hög motståndskraft mot väder tack vare aluminiumdränering.'
    },
    { 
        name: 'Duoline', 
        type: 'TRÄ/ALU', 
        specs: { Uw: '0.79-1.1', dB: '33-43', chambers: 'Hyb', depth: '68-88mm' }, 
        imageSrc: 'https://www.fonsterfaktor.se/lib/uid2kb/duoline-m6tk9v1o.png',
        description: 'Hybridfönster som förenar träets värme med aluminiumets hållbarhet. Perfekt för nordiskt klimat med minimalt underhållsbehov.'
    },
    { 
        name: 'Alu-MB70', 
        type: 'ALU', 
        specs: { Uw: '0.90-1.3', dB: '35-45', chambers: 'Alu', depth: '70mm' }, 
        imageSrc: 'https://www.fonsterfaktor.se/lib/uid2kb/MB70-m6tka4ha.png',
        description: 'Robust aluminiumsystem för alla väderförhållanden. Pulverlackerat för högsta kvalitet, lämpar sig för både privata hem och offentliga byggnader.'
    },
];

export const PRODUCTS: Product[] = [
    // Okna (fonster)
    { name: '1-LUFT(DH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_1-LUFT(DH).png' },
    { name: '1-LUFT(DKH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_1-LUFT(DKH).png' },
    { name: '1-LUFT(DKV)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_1-LUFT(DKV).png' },
    { name: '1-LUFT(DV)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_1-LUFT(DV).png' },
    { name: '1-LUFT(F)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_1-LUFT(F).png' },
    { name: '1-LUFT(FF)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_1-LUFT(FF).png' },
    { name: '1-LUFT(K)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_1-LUFT(K).png' },
    { name: '2-LUFT(DKV+DH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_2-LUFT(DKV+DH).png' },
    { name: '2-LUFT(DKV+DH) Sł.Ruchomy', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_2-LUFT(DKV+DH)_Sł.Ruchomy.png' },
    { name: '2-LUFT(DKV+DKH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_2-LUFT(DKV+DKH).png' },
    { name: '2-LUFT(DKV+F)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_2-LUFT(DKV+F).png' },
    { name: '2-LUFT(DV+DKH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_2-LUFT(DV+DKH).png' },
    { name: '2-LUFT(DV+DKH) Sł.Ruchomy', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_2-LUFT(DV+DKH)_Sł.Ruchomy.png' },
    { name: '2-LUFT(F+DKH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_2-LUFT(F+DKH).png' },
    { name: '2-LUFT(F+F)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_2-LUFT(F+F).png' },
    { name: '3-LUFT(DKV+DKV+DKV)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_3-LUFT(DKV+DKV+DKV).png' },
    { name: '3-LUFT(DKV+F+DKH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_3-LUFT(DKV+F+DKH).png' },
    { name: '3-LUFT(F+DKV+F)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_3-LUFT(F+DKV+F).png' },
    { name: '3-LUFT(F+F+F)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_3-LUFT(F+F+F).png' },
    { name: 'ALU 1-LUFT(DH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_1-LUFT(DH).png' },
    { name: 'ALU 1-LUFT(DKH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_1-LUFT(DKH).png' },
    { name: 'ALU 1-LUFT(DKV)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_1-LUFT(DKV).png' },
    { name: 'ALU 1-LUFT(DV)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_1-LUFT(DV).png' },
    { name: 'ALU 1-LUFT(F)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_1-LUFT(F).png' },
    { name: 'ALU 1-LUFT(FF)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_1-LUFT(FF).png' },
    { name: 'ALU 1-LUFT(K)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_1-LUFT(K).png' },
    { name: 'ALU 2-LUFT(DKV+DH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_2-LUFT(DKV+DH).png' },
    { name: 'ALU 2-LUFT(DKV+DH) Sł.Ruchomy', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_2-LUFT(DKV+DH)_Sł.Ruchomy.png' },
    { name: 'ALU 2-LUFT(DKV+DKH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_2-LUFT(DKV+DKH).png' },
    { name: 'ALU 2-LUFT(DKV+F)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_2-LUFT(DKV+F).png' },
    { name: 'ALU 2-LUFT(DV+DKH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_2-LUFT(DV+DKH).png' },
    { name: 'ALU 2-LUFT(DV+DKH) Sł.Ruchomy', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_2-LUFT(DV+DKH)_Sł.Ruchomy.png' },
    { name: 'ALU 2-LUFT(F+DKH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_2-LUFT(F+DKH).png' },
    { name: 'ALU 2-LUFT(F+F)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_2-LUFT(F+F).png' },
    { name: 'ALU 3-LUFT(DKV+DKV+DKV)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_3-LUFT(DKV+DKV+DKV).png' },
    { name: 'ALU 3-LUFT(DKV+F+DKH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_3-LUFT(DKV+F+DKH).png' },
    { name: 'ALU 3-LUFT(F+DKV+F)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_3-LUFT(F+DKV+F).png' },
    { name: 'ALU 3-LUFT(F+F+F)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_3-LUFT(F+F+F).png' },
    { name: 'ALU Drzwi Balkonowe 1-LUFT(DH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_Drzwi_Balkonowe_1-LUFT(DH).png' },
    { name: 'ALU Drzwi Balkonowe 1-LUFT(DKH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_Drzwi_Balkonowe_1-LUFT(DKH).png' },
    { name: 'ALU Drzwi Balkonowe 1-LUFT(DKV)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_Drzwi_Balkonowe_1-LUFT(DKV).png' },
    { name: 'ALU Drzwi Balkonowe 1-LUFT(DV)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_ALU_Drzwi_Balkonowe_1-LUFT(DV).png' },
    { name: 'TRÄ 1-LUFT(DH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_1-LUFT(DH).png' },
    { name: 'TRÄ 1-LUFT(DKH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_1-LUFT(DKH).png' },
    { name: 'TRÄ 1-LUFT(DKV)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_1-LUFT(DKV).png' },
    { name: 'TRÄ 1-LUFT(DV)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_1-LUFT(DV).png' },
    { name: 'TRÄ 1-LUFT(F)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_1-LUFT(F).png' },
    { name: 'TRÄ 1-LUFT(FF)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_1-LUFT(FF).png' },
    { name: 'TRÄ 1-LUFT(K)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_1-LUFT(K).png' },
    { name: 'TRÄ 2-LUFT(DKV+DH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_2-LUFT(DKV+DH).png' },
    { name: 'TRÄ 2-LUFT(DKV+DH) Sł.Ruchomy', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_2-LUFT(DKV+DH)_Sł.Ruchomy.png' },
    { name: 'TRÄ 2-LUFT(DKV+DKH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_2-LUFT(DKV+DKH).png' },
    { name: 'TRÄ 2-LUFT(DKV+F)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_2-LUFT(DKV+F).png' },
    { name: 'TRÄ 2-LUFT(DV+DKH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_2-LUFT(DV+DKH).png' },
    { name: 'TRÄ 2-LUFT(DV+DKH) Sł.Ruchomy', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_2-LUFT(DV+DKH)_Sł.Ruchomy.png' },
    { name: 'TRÄ 2-LUFT(F+DKH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_2-LUFT(F+DKH).png' },
    { name: 'TRÄ 2-LUFT(F+F)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_2-LUFT(F+F).png' },
    { name: 'TRÄ 3-LUFT(DKV+DKV+DKV)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_3-LUFT(DKV+DKV+DKV).png' },
    { name: 'TRÄ 3-LUFT(DKV+F+DKH)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_3-LUFT(DKV+F+DKH).png' },
    { name: 'TRÄ 3-LUFT(F+DKV+F)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_3-LUFT(F+DKV+F).png' },
    { name: 'TRÄ 3-LUFT(F+F+F)', category: 'Okna', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/fonster/fönster_TRÄ_3-LUFT(F+F+F).png' },

    // Drzwi (dorrar)
    { name: 'Balkong dörr 1-LUFT(DH)', category: 'Drzwi', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/dorrar/Balkong_dörr_1-LUFT(DH).png' },
    { name: 'Balkong dörr 1-LUFT(DKH)', category: 'Drzwi', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/dorrar/Balkong_dörr_1-LUFT(DKH).png' },
    { name: 'Balkong dörr 1-LUFT(DKV)', category: 'Drzwi', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/dorrar/Balkong_dörr_1-LUFT(DKV).png' },
    { name: 'Balkong dörr 1-LUFT(DV)', category: 'Drzwi', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/dorrar/Balkong_dörr_1-LUFT(DV).png' },
    { name: 'Balkong dörr TRÄ 1-LUFT(DH)', category: 'Drzwi', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/dorrar/Balkong_dörr_TRÄ_1-LUFT(DH).png' },
    { name: 'Balkong dörr TRÄ 1-LUFT(DKH)', category: 'Drzwi', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/dorrar/Balkong_dörr_TRÄ_1-LUFT(DKH).png' },
    { name: 'Balkong dörr TRÄ 1-LUFT(DKV)', category: 'Drzwi', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/dorrar/Balkong_dörr_TRÄ_1-LUFT(DKV).png' },
    { name: 'Balkong dörr TRÄ 1-LUFT(DV)', category: 'Drzwi', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/dorrar/Balkong_dörr_TRÄ_1-LUFT(DV).png' },
    { name: 'Balkong dörr TRÄ 2-LUFT(DKH+F)', category: 'Drzwi', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/dorrar/Balkong_dörr_TRÄ_2-LUFT(DKH+F).png' },
    { name: 'Dörr utåt Drzwi DZ.R+R.SL interior', category: 'Drzwi', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/dorrar/Dörr_utåt_Drzwi_DZ.R+R.SL_interior.png' },
    { name: 'Dörr utåt Drzwi DZ.R+R.SR interior', category: 'Drzwi', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/dorrar/Dörr_utåt_Drzwi_DZ.R+R.SR_interior.png' },
    { name: 'Dörr utåt Drzwi DZ.R1 interior', category: 'Drzwi', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/dorrar/Dörr_utåt_Drzwi_DZ.R1_interior.png' },
    { name: 'Dörr utåt Drzwi DZ.R2 interior', category: 'Drzwi', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/dorrar/Dörr_utåt_Drzwi_DZ.R2_interior.png' },

    // Terrassystem
    { name: 'Lyftglidparti HS.A.L', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Lyftglidparti_HS.A.L.png' },
    { name: 'Lyftglidparti HS.A.P', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Lyftglidparti_HS.A.P.png' },
    { name: 'Lyftglidparti HS.G2.L', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Lyftglidparti_HS.G2.L.png' },
    { name: 'Lyftglidparti HS.G2.P', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Lyftglidparti_HS.G2.P.png' },
    { name: 'Vik dörr F L FS202 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS202_interior.png' },
    { name: 'Vik dörr F L FS220 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS220_interior.png' },
    { name: 'Vik dörr F L FS303 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS303_interior.png' },
    { name: 'Vik dörr F L FS312 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS312_interior.png' },
    { name: 'Vik dörr F L FS321 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS321_interior.png' },
    { name: 'Vik dörr F L FS330 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS330_interior.png' },
    { name: 'Vik dörr F L FS404 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS404_interior.png' },
    { name: 'Vik dörr F L FS413 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS413_interior.png' },
    { name: 'Vik dörr F L FS431 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS431_interior.png' },
    { name: 'Vik dörr F L FS440 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS440_interior.png' },
    { name: 'Vik dörr F L FS505 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS505_interior.png' },
    { name: 'Vik dörr F L FS514 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS514_interior.png' },
    { name: 'Vik dörr F L FS541 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS541_interior.png' },
    { name: 'Vik dörr F L FS550 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS550_interior.png' },
    { name: 'Vik dörr F L FS606 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS606_interior.png' },
    { name: 'Vik dörr F L FS615 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS615_interior.png' },
    { name: 'Vik dörr F L FS651 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS651_interior.png' },
    { name: 'Vik dörr F L FS660 interior', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/Vik_dörr_F_L_FS660_interior.png' },
    { name: 'skjut dörr F+UP', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/skjut_dörr_F+UP.png' },
    { name: 'skjut dörr FF+UP', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/skjut_dörr_FF+UP.png' },
    { name: 'skjut dörr I7ED SL A', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/skjut_dörr_I7ED_SL_A.png' },
    { name: 'skjut dörr I7ED SL C', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/skjut_dörr_I7ED_SL_C.png' },
    { name: 'skjut dörr I7ED SL C L', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/skjut_dörr_I7ED_SL_C_L.png' },
    { name: 'skjut dörr I7ED SL L', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/skjut_dörr_I7ED_SL_L.png' },
    { name: 'skjut dörr UP+F', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/skjut_dörr_UP+F.png' },
    { name: 'skjut dörr UP+FF', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/skjut_dörr_UP+FF.png' },
    { name: 'skjut dörr UP+UP.SR(1.2)', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/skjut_dörr_UP+UP.SR(1.2).png' },
    { name: 'skjut dörr UP+UP.SR(2.1)', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/skjut_dörr_UP+UP.SR(2.1).png' },
    { name: 'skjut dörr UP-L', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/skjut_dörr_UP-L.png' },
    { name: 'skjut dörr UP.P', category: 'terrassystem', imageSrc: 'https://cdn.jsdelivr.net/gh/macmus40/f-nster-konfigurator-mini/public/images/terrassystem/skjut_dörr_UP.P.png' },
];

export const TRANSLATIONS: Record<string, any> = {
    sv: {
        header: 'OFFERTFÖRFRÅGAN',
        subheader: 'Professionellt fönstersystem för nordiskt klimat. Skapa din offertförfrågan nedan.',
        step1: 'VÄLJ PROFIL', step2: 'VÄLJ PRODUKT', step3: 'KONFIGURERA ENHETER',
        btn_send: 'SKICKA FÖRFRÅGAN', btn_add: 'LÄGG TILL ENHET', summary: 'DIN PROJEKTLISTA',
        empty: 'Välj en produkt för att börja.', ai: 'G-Assistant: Redo för teknisk analys.',
        width: 'BREDD (MM)', height: 'HÖJD (MM)', quantity: 'ANTAL', glassType: 'GLAS TYP',
        ventilation: 'VENTILATION', handle: 'HANDTAG', fName: 'FÖRNAMN', lName: 'EFTERNAMN', email: 'E-POSTADRESS',
        phone: 'TELEFONNUMMER', address: 'ADRESS (GATA & STAD)', message: 'MEDDELANDE / ÖVRIGT...',
        success: 'Förfrågan har skickats!', error: 'Ett fel uppstod vid sändning.', sending: 'SÄNDER...',
        vent_none: 'UTAN', vent_with: 'MED', profile_label: 'PROFIL', select_first: 'Vänligen välj en profil först!',
        nav_config: 'Konfiguration', nav_tech: 'Teknisk Analys',
        btn_confirm: 'LÄGG TILL I PROJEKTLISTA', btn_change: 'ÄNDRA', step_done: 'VALD',
        last_used: 'SENAST VALD',
        cat_okna: 'Fönster', cat_drzwi: 'Dörrar', cat_terrassystem: 'terrassystem',
        colorOut: 'FÄRG UTSIDA', colorIn: 'FÄRG INSIDA'
    },
    pl: {
        header: 'ZAPYTANIE OFERTOWE',
        subheader: 'Profesjonalne systemy okienne na nordycki klimat. Stwórz zapytanie ofertowe.',
        step1: 'WYBIERZ PROFIL', step2: 'WYBIERZ PRODUKT', step3: 'KONFIGURACJA JEDNOSTEK',
        btn_send: 'WYŚLIJ ZAPYTANIE', btn_add: 'DODAJ JEDNOSTKĘ', summary: 'LISTA PROJEKTOWA',
        empty: 'Wybierz produkt, aby rozpocząć.', ai: 'G-Assistant: Gotowy do analizy.',
        width: 'SZEROKOŚĆ (MM)', height: 'WYSOKOŚĆ (MM)', quantity: 'ILOŚĆ', glassType: 'TYP SZKŁA',
        ventilation: 'WENTYLACJA', handle: 'KLAMKA', fName: 'IMIĘ', lName: 'NAZWISKO', email: 'ADRES E-MAIL',
        phone: 'NUMER TELEFONU', address: 'ADRES (ULICA I MIASTO)', message: 'WIADOMOŚĆ / UWAGI...',
        success: 'Zapytanie zostało wysłane!', error: 'Wystąpił błąd podczas wysyłania.', sending: 'WYSYŁANIE...',
        vent_none: 'BEZ', vent_with: 'Z VENT', profile_label: 'PROFIL', select_first: 'Proszę najpierw wybrać profil!',
        nav_config: 'Konfiguracja', nav_tech: 'Analiza Techniczna',
        btn_confirm: 'DODAJ DO LISTY PROJEKTU', btn_change: 'ZMIEŃ', step_done: 'WYBRANO',
        last_used: 'OSTATNIO WYBRANY',
        admin_title: 'ADMIN: PRZYPISANIE PRODUKTÓW', admin_desc: 'Wybierz, które produkty są dostępne dla każdego profilu.',
        admin_profiles: 'ZARZĄDZANIE PROFILAMI', admin_acc: 'ZARZĄDZANIE DODATKAMI',
        admin_status: 'STATUS', admin_active: 'AKTYWNY', admin_disabled: 'WYŁĄCZONY',
        cat_okna: 'Okna', cat_drzwi: 'Drzwi', cat_terrassystem: 'systemy tarasowe',
        colorOut: 'KOLOR ZEWNĄTRZ', colorIn: 'KOLOR WEWNĄTRZ',
        admin_add_profile: 'DODAJ PROFIL', admin_add_product: 'DODAJ PRODUKT', admin_add_acc: 'DODAJ DODATEK',
        admin_name: 'NAZWA', admin_type: 'TYP', admin_image: 'URL OBRAZU', admin_desc_field: 'OPIS',
        admin_import_csv: 'IMPORTUJ Z CSV', admin_import_desc: 'Wgraj plik CSV, aby masowo dodać dane.',
        admin_import_btn: 'WYBIERZ PLIK', admin_download_template: 'POBIERZ SZABLON',
        admin_pass_title: 'DOSTĘP ZABLOKOWANY', admin_pass_desc: 'Wprowadź hasło administratora, aby kontynuować.',
        admin_pass_placeholder: 'HASŁO', admin_pass_btn: 'ZALOGUJ', admin_pass_error: 'Błędne hasło!'
    },
    en: {
        header: 'QUOTE REQUEST',
        subheader: 'Professional window systems for the Nordic climate. Create your quote request below.',
        step1: 'SELECT PROFILE', step2: 'SELECT PRODUCT', step3: 'CONFIGURE UNITS',
        btn_send: 'SEND INQUIRY', btn_add: 'ADD UNIT', summary: 'YOUR PROJECT LIST',
        empty: 'Select a product to begin.', ai: 'G-Assistant: Ready for technical analysis.',
        width: 'WIDTH (MM)', height: 'HEIGHT (MM)', quantity: 'QUANTITY', glassType: 'GLASS TYPE',
        ventilation: 'VENTILATION', handle: 'HANDLE', fName: 'FIRST NAME', lName: 'LAST NAME', email: 'EMAIL ADDRESS',
        phone: 'PHONE NUMBER', address: 'ADDRESS (STREET & CITY)', message: 'MESSAGE / NOTES...',
        success: 'Inquiry has been sent!', error: 'An error occurred while sending.', sending: 'SENDING...',
        vent_none: 'WITHOUT', vent_with: 'WITH', profile_label: 'PROFILE', select_first: 'Please select a profile first!',
        nav_config: 'Configuration', nav_tech: 'Technical Analysis',
        btn_confirm: 'ADD TO PROJECT LIST', btn_change: 'CHANGE', step_done: 'SELECTED',
        last_used: 'LAST SELECTED',
        admin_title: 'ADMIN: PRODUCT ASSIGNMENT', admin_desc: 'Select which products are available for each profile.',
        admin_profiles: 'PROFILE MANAGEMENT', admin_acc: 'ACCESSORIES MANAGEMENT',
        admin_status: 'STATUS', admin_active: 'ACTIVE', admin_disabled: 'DISABLED',
        cat_okna: 'Windows', cat_drzwi: 'Doors', cat_terrassystem: 'terrace systems',
        colorOut: 'COLOR OUTSIDE', colorIn: 'COLOR INSIDE',
        admin_add_profile: 'ADD PROFILE', admin_add_product: 'ADD PRODUCT', admin_add_acc: 'ADD ACCESSORY',
        admin_name: 'NAME', admin_type: 'TYPE', admin_image: 'IMAGE URL', admin_desc_field: 'DESCRIPTION',
        admin_import_csv: 'IMPORT FROM CSV', admin_import_desc: 'Upload a CSV file to bulk add data.',
        admin_import_btn: 'CHOOSE FILE', admin_download_template: 'DOWNLOAD TEMPLATE',
        admin_pass_title: 'ACCESS RESTRICTED', admin_pass_desc: 'Enter admin password to continue.',
        admin_pass_placeholder: 'PASSWORD', admin_pass_btn: 'LOGIN', admin_pass_error: 'Incorrect password!'
    }
};
